[workspace]
members = [
    "crates/kittynode",
    "crates/kittynode_core",
    "crates/kittynode_gui/src-tauri",
    "crates/kittynode_gui/src-web",
]
resolver = "2"

[workspace.package]
description = "A tool for managing decentralized node infrastructure at home."
license = "MIT"
version = "0.3.0"
edition = "2021"
repository = "https://github.com/kittynode/kittynode"
readme = "README.md"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.22.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin"]
# Which actions to run on pull requests
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = true
# Path that installers should place binaries in
install-path = "CARGO_HOME"
